[package]
name = "fastssh-desktop"
description = "FastSSH desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.104"
fastssh = { path = "../server" }
tauri = { version = "2.12.1", features = [] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }
